### ISSUE TITLE
Cordova iOS won't build.

### ISSUE THREAD

**Issue by betorobson** [ropilz/phonegap-parse-plugin#2]
Hi,

I'm facing a issue to build my project after install this plugin. Could anyone help me please.
I already have remove and add my iOS platform, but it won't build.

This is my log error from build process.

ld: framework not found Bolts
clang: error: linker command failed with exit code 1 (use -v to see invocation)

*\* BUILD FAILED **

The following build commands failed:
    Ld build/emulator/Quero\ Mais\ Saúde.app/Quero\ Mais\ Saúde normal i386
(1 failure)
Error code 65 for command: xcodebuild with args: -xcconfig,/Users/roberto/web/queromaissaude.sautil.com.br/natura-project/mobile-app/platforms/ios/cordova/build-debug.xcconfig,-project,Quero Mais Saúde.xcodeproj,ARCHS=i386,-target,Quero Mais Saúde,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/roberto/web/queromaissaude.sautil.com.br/natura-project/mobile-app/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/roberto/web/queromaissaude.sautil.com.br/natura-project/mobile-app/platforms/ios/build/sharedpch
ERROR building one of the platforms: Error: /Users/roberto/web/queromaissaude.sautil.com.br/natura-project/mobile-app/platforms/ios/cordova/build: Command failed with exit code 2
You may not have the required environment or OS to build this project
Error: /Users/roberto/web/queromaissaude.sautil.com.br/natura-project/mobile-app/platforms/ios/cordova/build: Command failed with exit code 2
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:131:23)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1080:5)

**Comment by bhavikup** [comment]
Hello,
I am having the same error. Did you by chance fix it?

**Comment by betorobson** [comment]
Actually, I'm not using this plugin any more , instead use https://github.com/grrrian/phonegap-parse-plugin.

I strongly recommend remove ropilz before install grrrian version.
